name: my_link_space
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  # Use only one reference for flutter_secure_storage
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  json_serializable: ^6.8.0
  json_serializer: ^0.2.0
  getwidget: ^4.0.0
  flutter_intro: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  go_router: ^14.2.7
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  redacted: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_at: ^2.1.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.12
  get_it: ^7.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/token_spaces.svg
