import 'package:flutter/material.dart';

const chipBackgroundLight = Color.fromARGB(255, 215, 215, 215);
const Color primaryLightColor = Color.fromRGBO(132, 45, 247, 1);
const Color primaryContainerLightColor = Color(0xffd9b3ff);
const Color secondaryLightColor = Color(0xff845ec2);
const Color secondaryContainerLightColor = Color(0xffdfd2ff);
const Color tertiaryLightColor = Color(0xff714bdf);
const Color errorLightColor = Color(0xffd32f2f);
const Color errorContainerLight = Color(0xFFF39C9C);
const Color surfaceLightColor = Color(0xFFEDE7FF);
const Color appBarBackgroundLightColor = Color.fromARGB(255, 232, 232, 232);
const Color scaffoldBackgroundLightColor = Color.fromARGB(255, 232, 232, 232);
const Color selectedItemLightColor = Color(0xff9b5fe0);
const Color unselectedItemLightColor = Colors.grey;
const Color cardLightBackgroundColor = Colors.white;
const Color textFieldFillColorLight = const Color.fromARGB(255, 205, 205, 205);

const Color textFieldFillColorDark = Color.fromARGB(255, 73, 73, 73);
const chipBackgroundDark = Color.fromARGB(255, 64, 64, 64);
const Color cardDarkBackgroundColor = const Color(0xFF2D2D2D);
const Color primaryDarkColor = Color(0xff9b5fe0);
const Color appBarBackgroundDarkColor = Color(0xFF1E1E1E);
const Color scaffoldBackgroundDarkColor = Color(0xFF1E1E1E);
const Color primaryContainerDarkColor = Color(0xff6e4edb);
const Color secondaryDarkColor = Color(0xff967dff);
const Color secondaryContainerDarkColor = Color(0xff4136b2);
const Color tertiaryDarkColor = Color(0xff714bdf);
const Color errorDarkColor = Color(0xffd32f2f);
const Color errorContainerDark = Color(0xffcf6679);
const Color surfaceDarkColor = Color(0xFF1E1E1E);
const Color selectedItemDarkColor = Color(0xff9b5fe0);
const Color unselectedItemDarkColor = Colors.grey;
